src/components/functional/ActionUrlHandler.js, src/handlers/auth/auth.js, src/pages/auth/emailVerification/molecules/VerifyEmail.jsx, src/pages/auth/forgotPassword/molecules/ForgotPasswordForm.jsx, src/pages/auth/resetPassword/molecules/ResetPasswordForm.jsx, src/routes/AuthRoutes.jsx, src/setup/routesManager/ProtectEmailVerification.jsx, src/setup/slices/auth/authSlice.js
- Fixed bug in email verification system
-  Fixed bug in reset password system
- Fixed bug in forgot password system
- Completed sign in process
=> Completed app's authentication flow

src/components/ui/InputGroup.jsx, src/handlers/auth/auth.js, src/layouts/auth/Layout.jsx, src/layouts/index.js, src/layouts/private/Layout.jsx, src/layouts/private/partials/BottomBar.jsx, src/layouts/private/partials/Header.jsx, src/layouts/private/partials/SideBar.jsx, src/pages/auth/components/AuthContainer.jsx, src/pages/auth/signup/molecules/SignUpForm.jsx, src/routes/PrivateRoutes.jsx, src/setup/slices/user/userSlice.js, src/styles/global/Global.styled.js, src/styles/reusable/elements.styled.js
- Created private layout and made it responsive.
- Name and Image are dynamically displayed
- Added name field during registration
- Updating photoURL during custom registration using dicebeat
=> Completed Private Area Layout

package-lock.json, package.json, src/pages/private/dashboard/molecules/Analytics.jsx, src/pages/private/dashboard/molecules/History.jsx, src/pages/private/dashboard/molecules/TopStats.jsx
=> Feat: Dashboard Update

src/App.jsx, src/main.jsx, src/pages/auth/verifiedEmail/molecules/VerifiedEmail.jsx, src/routes/routesManager/PrivateRoutes.jsx, src/routes/routesManager/ProtectEmailVerification.jsx, src/setup/redux/slices/auth/authSlice.js
We might need redux persist to persist some data, however we fixed the issue already
=> fix: fixed issue with protected routes

src/assets/theme1.svg, src/assets/theme2.svg, src/components/ui/TextAreaInputGroup.jsx, src/components/ui/index.js, src/layouts/private/partials/BottomBar.jsx, src/layouts/private/partials/SideBar.jsx, src/pages/private/components/Banner.jsx, src/pages/private/components/PrivateInnerContainer.jsx, src/pages/private/gemspolls/index.jsx, src/pages/private/gemspolls/molecules/ChartsSection.jsx, src/pages/private/gemspolls/molecules/MobileChartsSection.jsx, src/pages/private/gemspolls/molecules/ProfileHero.jsx, src/pages/private/gemspolls/molecules/SingleChart.jsx, src/pages/private/gemspolls/molecules/WebChartsSection.jsx, src/pages/private/index.js, src/pages/private/profile/index.jsx, src/pages/private/profile/molecules/ProfileCard.jsx, src/pages/private/settings/index.jsx, src/pages/private/settings/molecules/AccountSettings.jsx, src/pages/private/settings/molecules/ChangePasswordSettings.jsx, src/pages/private/settings/molecules/InterfaceThemeSettings.jsx, src/pages/private/settings/molecules/SettingsNavigation.jsx, src/pages/private/settings/molecules/index.js, src/routes/PrivateRoutes.jsx
This PR: Dashboard Sections Updates
=> Feat: Dashboard Sections Update

src/components/ui/SelectInputGroup.jsx, src/pages/private/dashboard/molecules/History.jsx, src/pages/private/dashboard/molecules/TopStats.jsx, src/pages/private/gemspolls/molecules/ProfileHero.jsx, src/pages/private/hype/molecules/SendHype.jsx, src/pages/private/profile/molecules/ProfileCard.jsx, src/pages/private/settings/molecules/AccountSettings.jsx
This PR: dashboard updates, little adjustments
=> feat:dashboard updates

src/pages/private/hype/molecules/SendHype.jsx
This PR
Send Hype Layout Adjustments
=> Beyond logic

src/layouts/private/partials/Header.jsx, src/pages/private/hype/molecules/SendHype.jsx, src/pages/private/hype/molecules/samplehypes.js
removed the console.log as it keeps running in the background and outputing details
=> feat: remove console.log

src/pages/private/hype/molecules/SendHype.jsx, src/pages/private/hype/molecules/samplehypes.js
=> feat: hypes send updates

src/pages/private/hype/molecules/SendHype.jsx, src/pages/private/profile/molecules/ProfileCard.jsx
This PR: send hype updates, dashboard updates
=> feat: hype send updates, dashboard updates, styles

index.html
This PR: disable zooming on mobile devices
=> feat: disable zooming on mobile devices

src/pages/private/hype/molecules/SendHype.jsx
PR: increase the z-index of the hype sent success modal
=> style: increase the z-index of the hype sent success modal

src/pages/private/profile/molecules/ProfileCard.jsx
This PR: texts fitting with CSS: word-break: break-word
=> styles: updates

src/pages/private/hype/molecules/SendHype.jsx
=> feat: update to send hype

src/layouts/private/Layout.jsx, src/layouts/private/partials/BottomBar.jsx, src/pages/private/dashboard/molecules/TopStats.jsx, src/pages/private/hype/molecules/SendHype.jsx
This Pr: style:dashboard layout improvement, updates
=> style:dashboard layout improvement, updates

src/layouts/private/partials/BottomBar.jsx
This PR: style: revert footer Bottom position back to fixed
=> style: revert footer Bottom position back to fixed

src/layouts/private/Layout.jsx
style: layout updates - revert some added css update
=> style: layout updates - revert update

src/pages/private/hype/molecules/SendHype.jsx
This PR :feat: send hype updates, styling
=> feat: send hype updates, styling

src/pages/private/hype/molecules/SendHype.jsx
This PR: feat: send hype updates
=> feat: send hype update

src/pages/private/hype/molecules/SendHype.jsx
This PR: feat:send hype updates
=> feat:send hype updates

src/pages/private/hype/molecules/SendHype.jsx
feat:send hype updates minor fixes
=> feat:send hype updates - minor fixes

src/routes/AdminRoutes.jsx, src/routes/routesManager/PrivateRoutes.jsx, src/routes/routesManager/ProtectAdmin.jsx, src/setup/redux/slices/auth/authSlice.js, src/setup/redux/slices/auth/extraReducers.js
Setup admin role for **control@catalyst.africa** and protected routes for admin
=> feat: setup admin role for control@catalyst.africa and protected routes for admin

src/layouts/public/Layout.jsx, src/pages/public/components/Footer.jsx, src/pages/public/components/Intro.jsx, src/pages/public/components/PublicContainer.jsx, src/pages/public/home/molecules/HeroSection.jsx, src/pages/public/home/molecules/HomeIntro.jsx, src/pages/public/hypemessage/index.jsx, src/pages/public/index.js, src/pages/public/terms/index.jsx, src/pages/public/terms/molecules/Terms.jsx, src/routes/PublicRoutes.jsx
=> feat: external pages update, and code refactor, home page, terms page
